# Based on ./gatekeeper-operator/bundle.Dockerfile
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as builder-runner
RUN microdnf install -y skopeo jq python3 python3-pip
RUN pip3 install ruamel.yaml==0.17.9

# Use a new stage to enable caching of the package installations for local development
FROM builder-runner as builder

COPY bundle-hack .
COPY marin3r/bundle/manifests /manifests/
COPY marin3r/bundle/metadata /metadata/

RUN ./update_bundle.sh

FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=marin3r-operator
LABEL operators.operatorframework.io.bundle.channels.v1=alpha
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.34.1
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

# TODO: cleanup if not needed
LABEL com.redhat.component="marin3r-operator-bundle-container" \
      name="3scale-mas/marin3r-operator" \
      version="alpha" \
      summary="Lighweight, CRD based Envoy control plane for Kubernetes" \
      description="Lighweight, CRD based Envoy control plane for Kubernetes" \
      distribution-scope="public" \
      io.k8s.description="MARIN3R operator" \
      release="v0.13.2" \
      url="https://github.com/3scale-sre/marin3r" \
      vendor="Red Hat"
#      io.k8s.display-name="MARIN3R" \
#      io.openshift.expose-services="" \
#      io.openshift.tags="3scale, api, envoy" \
#      upstream_repo="${CI_MARIN3R_UPSTREAM_URL}" \
#      upstream_ref="${CI_MARIN3R_UPSTREAM_COMMIT}" \
#      maintainer="rvazquez@redhat.com"

# Copy files to locations specified by labels.
COPY --from=builder /manifests /manifests/
COPY --from=builder /metadata /metadata/
COPY marin3r/bundle/tests/scorecard /tests/scorecard/